# vis = False
use_crowd_hat = False
prepare_training_data = False
S = 64
L = 256
K = 4
alpha_ba = 16384
alpha_bc = 1
global_dic = {}
train_dic = {}
training_data_root = './training_data'
weights_root = './weights'
vis_root = './vis'
result_root = './results'

img_root = r'/home/ubuntu/dataset/nwpu/images'
json_root = r'/home/ubuntu/dataset/nwpu/Points'
nwpu_test = r'/home/ubuntu/dataset/test'
# qnrf_img = r'/home/ubuntu/dataset/qnrf/jpegs'
# qnrf_json = r'/home/ubuntu/dataset/qnrf/jsons'
# sha_img = r'/root/autodl-tmp/dataset/sha_img'
# sha_json = r'/root/autodl-tmp/dataset/sha_json'
# shb_img = r'/root/autodl-tmp/dataset/shb_img'
# shb_json = r'/root/autodl-tmp/dataset/shb_json'
